version: '3.7'

services:
  web:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/site-contents:/var/www/html/:ro
